### ISSUE TITLE
MariaDB No Longer Supported?

### ISSUE THREAD

**Issue by ed-iv** [TablePlus/tabledump#20]
Similar to issue #17 except with MariaDB. When trying to dump as Laravel migration I'm getting 'Rerror:  MariaDB not supported'. Have always been using MariaDB and this worked for me in the past.

**Comment by dmachiavello** [comment]
I've also been using this with MariaDB quite a few times. is there a way to disable the mariadb check? (in my case the schema isn't doing anything MariaDB specific)

**Comment by dmachiavello** [comment]
It's a workaround, but i created a new MySQL connection to the same database and got what i needed. Hope this helps anyone else in the future.

**Comment by huyphams** [comment]
I've merged the PR from @dmachiavello and release the new version, you guy can update it with Command + L. Thanks!
