### ISSUE TITLE
Incorrect "smallint" definition when exporting to Laravel

### ISSUE THREAD

**Issue by mattias-sanfridsson** [TablePlus/tabledump#4]
Columns of the type "smallint" currently use a `$table->smallint` method which doesn't exist in Laravel. This should be `$table->smallInteger`.

**Comment by marandy0905** [comment]
I think this is fixed? in Commit 7864260f66c41f6ee9abe4a9add54c4852732153

**Comment by mattias-sanfridsson** [comment]
Looks like it 👍
